### ISSUE TITLE
Handle query params on website

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one#129]
## Summary
The website currently fails to render any page if the url contains a query param at the end (e.g. https://tram-one.io/?example)

Sometimes these query params are auto populated by a service that would share this url (like Facebook ads), and will fail approval because it returns a 404 page.

Since we are not using query params for the site, any query params should be ignored or removed.

## Potential implementation
The site is generated through docma, so hopefully there is some configuration there to disable query param routing, or just ignore it.

**Comment by jamesallured** [comment]
I can give this one a look! 🙂

**Comment by JRJurman** [comment]
This seems to be a bug on docma's side, not a configuration, I've posted an issue on their repo here: https://github.com/onury/docma/issues/92

It's not obvious if a fix is made if it will be merged in, I believe I have a local copy that fixes it, but it almost looks like it's intentional.

**Comment by JRJurman** [comment]
Since changing the site away from docma, this has become a non-issue.
