### ISSUE TITLE
hr tag needs to be self closing when adding to the DOM

### ISSUE THREAD

**Issue by chtinahow** [Tram-One/tram-one#162]
## Summary
The current implementation for the `hr` tag states that the tag itself doesn't need to be self closing, however, in practice with tram-one, it needs to be self closing into order to work.
e.g. a piece of code that looks like: 
```
<h2>Round 1</h2>
<hr>
```
renders as 
![image](https://user-images.githubusercontent.com/8568993/125009680-006c8d00-e033-11eb-839d-1553edc0d082.png)

**Comment by JRJurman** [comment]
(we could also try to read forward and determine if there is no closing version of this tag, to make it self-closing, but that would be significantly harder to build).
