### ISSUE TITLE
Nested Routing

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one#32]
## Summary
React router is really cool, and lets you easily describe wrapping page elements around components. 

```javascript
<Route path="/" component={PageChrome}>
  <Route path=":user" component={UserPage} />
</Route>
```

Doing this in Tram-One would require a possibly breaking change to `addRoute`, and definitely a breaking change to what properties top-level / low-level view take in. This might be a sign that there shouldn't be a distinction between top and low level views.

**Comment by JRJurman** [comment]
It's possible that all views should take in `attrs`, and `children`, where top level components are given `attrs.store`, `attrs.actions`, and `attrs.params`, for the things that they would receive on rendering.

**Comment by JRJurman** [comment]
Thoughts @danudesandstorm, @ethanjurman ?

**Comment by ethanjurman** [comment]
Personally, I think all components should be able opt-in and out of receiving store props.
As far as wrapping page elements, why not make `addRouteWrapper`... to prevent breaking changes.
Or have `addRoute` take in a third param `app.addRoute("/", UserPage, WrappingComponent)`

**Comment by JRJurman** [comment]
^ I like this, and for me, this would be the most common use case, however, this only works one level deep...

**Comment by DanudeSandstorm** [comment]
Using a pure nested objects
```
router.add({
    "path": "/",
    "component": homecomp,
    "children": 
    [
        {
            "path": "users",
            "component": users_comp
            "children": {
                "path": ":user",
                "component": individual_users_comp
            }
        },
        {
            "path": "shoes",
            "component": shoes_comp
        }
    ]
})
```
Using a nested route function approach (like react but not xml)
```
Route("/", comp, [
    Route("users", user_comp, [
        Route(":user", individual_users_comp)
    ]),
    Route("shoes", shoes_comp)
])
```

**Comment by ethanjurman** [comment]
Thinking over it, the nested route function approach seems like the way to go.

**Comment by JRJurman** [comment]
I don't like having this `Route` object. But I understand that it's easier to read than a list, and easier to write than an object.

**Comment by JRJurman** [comment]
Talked it over with @DanudeSandstorm, here are the following notes:
1) `Tram.route` is a static function, which takes in 
* `path`, the route to add (i.e. `'/'`, `':user'`)
* `component`, a view function
* `children`, a list of Tram.route objects

It returns an object that literally maps it's arguments to named props, the true intent of the function is to make the following syntax cleaner to write:

```javascript
const Tram = require('tram-one')
const app = new Tram()
app.addRoutes(
  route('/', homePage, [
    route(':user', userPage),
    route(':user/settings', settingPage)
  ]
)
```

2) All views will take in 5 props
* `attrs`, nothing for top level components, props that are passed in for sub-views
* `children`, any child views created when using the router, or when writing view components
* `store`, hover-engine store with up-to-date state
* `actions`, hover-engine actions
* `params`, path and query params from the url

It's more bloated, but it means that all views should be connected, and don't depend on passing props from the very top to the very bottom, if only sub views care about triggering certain actions.

**Comment by JRJurman** [comment]
Implementation-wise, I'm not 100% sure how we give each view an instance of `store, actions, params`...

**Comment by ethanjurman** [comment]
You could export `engine` from `main.js` and have views opt to connect to the engine using some `connect` function that provides a [Higher order component](https://reactjs.org/docs/higher-order-components.html) to feed the engine, [similar to how general store does it] (https://github.com/HubSpot/general-store/blob/master/README.md#connect)

**Comment by JRJurman** [comment]
Hmmm... I'm not sure I want to require more code to write for each component you create. Even so, I just don't know how when we build out these views, we are able to give them more stuff... (Not sure how the connect function will help make that easier or harder).

**Comment by JRJurman** [comment]
We may have to look at how we are using rbel, since that is the magic that provides the first two arguements https://github.com/aaaristo/rbel

**Comment by DanudeSandstorm** [comment]
I'm still looking into what it entails, but react-router has significantly overhauled their design (again) in v4 https://www.npmjs.com/package/react-router4 . Although I really like the concept of nested route function

**Comment by ethanjurman** [comment]
@JRJurman What's the status of this?

**Comment by JRJurman** [comment]
Let me mull over this for a bit... The API has changed significantly since we first started talking about this ticket.
