### ISSUE TITLE
Expose Hover-Engine's addListener

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one#33]
## Summary
It would be useful to have a chrome-extension to listen for state changes from hover-engine (similar to the redux chrome-extension). In order to even start that work, we need to be able to add listeners to tram-one state changes.

This should be pretty similar to Tram-One's addActions, where we just call `this.engine.addListener`
https://github.com/Tram-One/tram-one/blob/b82d2feda534031f85b97124d4cb7d2bc650eeeb/tram-one.js#L23-L32

Docs for `addListener`
https://github.com/Tram-One/hover-engine#addlistenerlistener

## Todo
For this ticket we need the following things:
* a new function `addListener`, it should take in a listener and return `this`
* there should be an assert that the listener is a function
* it should call `this.engine.addListener` with the passed in listener

We also want the following test:
* on calling an action, the custom listener should be called (you don't have to check with what, just that it was)

### Example Custom Page
You'll need a custom page that triggers an action once when it loads (and only once when it loads)
```javascript
const pageWithAction = (store, actions) => { 
  if (store.switch) { actions.toggle() } 
  return html`<div>${store.switch}</div>`
}

const switchAction = {
  init: () => true
  toggle: () => false
}
```

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. Can you guide me ?

**Comment by JRJurman** [comment]
@KhushilMistry sure! I've updated the docs for the ticket. I realized while fleshing it out more that the required test makes it a bit more challenging than easy. If you're still up for it, it's up for grabs!

**Comment by KhushilMistry** [comment]
@JRJurman Can you elaborate a custom page part ? Means how will I trigger all the listeners after triggering any action ? How can I know that an action is triggered ?

**Comment by JRJurman** [comment]
You can use the custom page that I listed in the end of the ticket description. Listeners should automatically be triggered when an action is called (in this case, `actions.toggle()` calls the `toggle` action). 

You'll have to verify with Jasmine that your listener was called (you can use `.toHaveBeenCalled` method). You don't really need to test that the action was triggered, since I believe that's already verified in another test.

**Comment by JRJurman** [comment]
Thinking about it more, the listener you add could just be a Jasmine Spy. For a similar example, you can see the Hover Engine tests:

https://github.com/Tram-One/hover-engine/blob/219d11553e0b4b4301d1089d387c435431c3c464/specs/hover-engine-specs.js#L103-L110

```javascript
    it('should call single listener', () => {
      const spy = jasmine.createSpy('listener')
      engine.addListener(spy)
      engine.addActions(ag.singleActionGroup())
      engine.notifyListeners()


      expect(spy).toHaveBeenCalled()
    })
```

**Comment by KhushilMistry** [comment]
So For this issue, I have to add addListener function in tram-one.js and Test Case with Jasmin in ./tests/specs/tram-spec.js, Right ?

**Comment by JRJurman** [comment]
@KhushilMistry yep! If need be, work on one at a time, I don't mind reviewing in-progress PRs!

**Comment by KhushilMistry** [comment]
@JRJurman I have made PR. Please look at it #54
