### ISSUE TITLE
Badges for Readme

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one#34]
## Summary
It would be cool to have badges on the top of the README page, like other projects have.
Not sure which ones to add, but would be willing to review any PRs for any that people want to add.

**Comment by JRJurman** [comment]
For example projects with badges
- https://github.com/vuejs/vue
- https://github.com/facebook/react

**Comment by supergooddave** [comment]
This is my first pull request, let me know if I didn't do it right.

**Comment by JRJurman** [comment]
Resolved by #43
