### ISSUE TITLE
Support for custom empty element tag closing

### ISSUE THREAD

**Issue by ethanjurman** [Tram-One/tram-one#36]
https://developer.mozilla.org/en-US/docs/Glossary/Empty_element

It's redundant and obnoxious to close custom elements that do not take in or make use of children elements. @JRJurman is this possible?

**Comment by JRJurman** [comment]
We should definitely look into this... The issue is either in https://github.com/Tram-One/bel-create-element or in https://github.com/aaaristo/rbel

**Comment by ethanjurman** [comment]
We could provide a function that checks for nested tags and properly closes them [before sending to bel / rbel](https://github.com/Tram-One/tram-one/blob/master/tram-one.js#L94)... but then the question is whether we are sacrificing performance for what would be a less than optimal solution.

Actually would the performance there really matter?

**Comment by JRJurman** [comment]
turns out it was hyperx, pr in the works: https://github.com/choojs/hyperx/pull/58
