### ISSUE TITLE
Use Tram-One Logo in Readme

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one#37]
## Summary
We should put the logo in the README. Other projects do it, and our logo is super-awesome!

## Other projects
- https://github.com/sindresorhus/eslint-plugin-unicorn
- https://github.com/sindresorhus/xo
- https://github.com/vuejs/vue

**Comment by JRJurman** [comment]
@ethanjurman eh, I think that is a separate issue, and for this ticket, we can settle on just using v3's svg or png

**Comment by DanudeSandstorm** [comment]
I put in a pr which just places the svg logo in the main directory. Then I'll create a PR that updates the readme to point to that

**Comment by JRJurman** [comment]
@DanudeSandstorm I'm tempted to believe that's not wholly required? I think it would be better if we pointed to the github repo itself.

**Comment by JRJurman** [comment]
Oh I misread what you wrote. @ethanjurman and I talked, and I think it'll be best if we just hard-code point to the v3 folder. Rather than having two copies of the tram-one logo svg in that repo.

**Comment by DanudeSandstorm** [comment]
Alright, that's an easy change. The reason I thought to have lifted out the svg into the main folder was if it changes versions and we point to the logo on multiple of the readmes it will be a pain to change.

You can also solve the issue by simply removing the svg inside the v3 folder.

**Comment by JRJurman** [comment]
@DanudeSandstorm yeah, I've thought back and forth on this, and I decided that the nature of the logo shouldn't change too much from here on out, and if a repo points to an old version of a logo, then it probably isn't getting updated enough to be referring to new versions. Besides, I think having a copy of the svg in two places is ugly and unclear.

**Comment by JRJurman** [comment]
Either way, thanks for tackling this one @DanudeSandstorm !
