### ISSUE TITLE
Tram One Performance Tests

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one#39]
## Summary
It would be useful to have performance tests comparing Tram-One to other frameworks. It would also be good to verify that changes don't make the project any slower (without a good reason)!

Not really sure what tests we would do, this requires some research into what other frameworks are doing for performance tests.

**Comment by dropofwill** [comment]
May be a good choice https://github.com/krausest/js-framework-benchmark#optional-31-contributing-a-new-implementation

**Comment by JRJurman** [comment]
It would be cool to create an artifact for this per version (just like we do for our file sizes).
