### ISSUE TITLE
More Examples!

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one#40]
## Summary
Lots of frameworks have simple examples (pointing to other repos) of their framework in use. 
Anyone who builds something in Tram-One is welcome to advertise it on the README!

I'll add a section to the README where we can list different repos.

### Note
These are not the examples that can be run in the examples folder, the intent here is for full fledge examples in their own repo.

**Comment by KhushilMistry** [comment]
Hey, I want to contribute by making one Image Carousel Example. Should I directly fork this Repo and make one Example in example folder or make this example separately with Tram-One Express ?

**Comment by JRJurman** [comment]
Hey @KhushilMistry, an Image carousel sounds awesome! If it's small enough than I'd be fine putting it in the examples folder. If you wanted to make a full blown web-app, then we should just link it in the Examples section in the README.

**Comment by KhushilMistry** [comment]
Let me try my hand on small one. If I really like that, I will definitely build some Carousel module with multiple features over Tram-one.

**Comment by KhushilMistry** [comment]
hey, I have made one Example : on PR #49 Can you look at it ?
