### ISSUE TITLE
Change Documentation to use Self-Closing Tags

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one#46]
## Summary
Now that Tram-One supports self-closing tags, we should update all the documentation and examples that don't use children to be self-closing.

### Example
In the following example we can change `<footer></footer>` to `<footer/>`
https://github.com/Tram-One/tram-one/blob/455c1fd06d7e1d3ffacd3898399be02bd62edc34/examples/using-custom-elements/chrome.js#L11-L17

**Comment by robbawebba** [comment]
I would love to help with this issue if it's up for grabs still!

**Comment by JRJurman** [comment]
Thanks @robbawebba taking a look at the PR now.
