### ISSUE TITLE
SVG example

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one#51]
## Summary
It would be awesome if we could have an example showing tram-one's support for SVGs. Hyperapp has a neat little clock (codepen here: https://codepen.io/hyperapp/pen/PWMBLp?editors=0010)

I would not be opposed showing the same example with Tram-One logic. This should probably end up in the examples folder

**Comment by KhushilMistry** [comment]
Hey, Can I work on this ?

**Comment by ethanjurman** [comment]
@KhushilMistry what did you have in mind as far as an svg example? Looking at the clock one, we probably don't need something as complex, but it wouldn't hurt either.

**Comment by KhushilMistry** [comment]
We can make proper clock with Seconds, Minutes and Hour Hands. Can also Display 1 to 12.

**Comment by ethanjurman** [comment]
You probably don't _need_ to do 1 to 12, just some dashes or something would be fine... anything that you get working tho would be cool.

**Comment by ethanjurman** [comment]
Can we close this?

**Comment by JRJurman** [comment]
@ethanjurman thanks for catching this, yes yes we can.

Resolved by #69
