### ISSUE TITLE
Badge for Build Size

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one#52]
## Summary
It would be awesome if we could have a custom `umd` and `module` size badges.

## Possible Implementation
I'm not 100% sure what the best way to do this is, but I believe one way we could go about this is by using the [shields project](https://github.com/badges/shields) (which is used for the other badges anyways) as a dependency. On builds (or post-build) we read the size of the distributables, and generate the images using the library. The github readme could then point to these local assets for the build size badges.

**Comment by thatbraxguy** [comment]
I gotchu
