### ISSUE TITLE
RunKit fails (missing domino dependency)

### ISSUE THREAD

**Issue by JRJurman** [Tram-One/tram-one#85]
## Summary
In the **Try it in your browser** section of npm, there is a link to RunKit. For some reason however, it fails not being able to find `domino` (our dependency used for making a virtual dom in the browser).

Domino should be used in this node environment, but for some reason, it's not quite working... Needs investigation.

https://npm.runkit.com/tram-one
Screenshot:
![image](https://user-images.githubusercontent.com/326557/36346598-295ee76a-140f-11e8-9952-146461fd41c2.png)

**Comment by JRJurman** [comment]
Potentially, this could be because the default build points to the UMD (which is made for the browser, and does not bundle domino). 

## Possible Solutions
- make default export esm
- somehow point to the esm export
- have a more proper error when domino is not found (something along the lines of 
```
ERROR: expected document object, but not found. if this is node, use the esm export"
```
)

**Comment by JRJurman** [comment]
Hmmmm... maybe not, running the follow presents another require error
```javascript
var tramOne = require("tram-one/dist/tram-one.esm.js")
```
```
Error: Cannot find module 'rbel'
```

**Comment by JRJurman** [comment]
Definitely leaning towards making the default export the es module.

**Comment by JRJurman** [comment]
I think the final solution to this is to make ESM the default export. This would be consistent with other libraries default export, however would be another breaking change. I'm want to wait until we resolve #76 , which itself is probably a breaking change, to do that release

**Comment by JRJurman** [comment]
Okay... now it's failing because the `rbel` version is behind on RunKit... Aside from being the default, I'm really losing faith in RunKit, and strongly thinking about making an online evaluator.

**Comment by tolmasky** [comment]
Hi Jesse,

We've gone ahead and fixed the rebl dependency -- really sorry for the delay on that (we had a few hiccups at the beginning of the year that left a couple holes in our package support). I try to regularly search through github issues to pick up on problems like the one you're experiencing, but if you have any issue like that again, don't hesitate to drop me a line directly at francisco@runkit.com so I can fix it faster for you.

Thanks and sorry again for the overly long time it took to get this working!

Francisco

**Comment by JRJurman** [comment]
@tolmasky thanks a bunch for the work, and finding this ticket and commenting! 
Everything looks shiny now 👍
